"""
This type stub file was generated by pyright.
"""

import _jpype
from ._jinit import *
from ._jpackage import *
from ._jproxy import *
from ._core import *
from . import _core, _jarray, _jcollection, _jexception, _jio, _jmethod, _jthread, nio, protocol, types
from ._gui import *
from ._classpath import *
from ._jclass import *
from ._jobject import *
from .types import *
from ._jcustomizer import *

__all__ = ['java', 'javax', '_jarray', '_jexception', 'nio', '_jmethod', '_jcollection', '_jio', 'protocol', '_jthread']
__version__ = ...
__version_info__ = ...
java = ...
javax = ...
JMethod = ...
JField = ...
if hasattr(_jpype, 'bootstrap'):
    ...
