"""
This type stub file was generated by pyright.
"""

import os as _os
import typing

__all__ = ['addClassPath', 'getClassPath']
_CLASSPATHS = ...
_SEP = ...
def addClassPath(path1: typing.Union[str, _os.PathLike]) -> None:
    """ Add a path to the Java class path

    Classpath items can be a java, a directory, or a
    glob pattern.  Relative paths are relative to the 
    caller location.

    Arguments:
      path(str):

    """
    ...

def getClassPath(env: bool = ...) -> str:
    """ Get the full Java class path.

    Includes user added paths and the environment CLASSPATH.

    Arguments:
      env(Optional, bool): If true then environment is included.
        (default True)
    """
    ...

