"""
This type stub file was generated by pyright.
"""

__all__ = ['setupGuiEnvironment', 'shutdownGuiEnvironment']
def setupGuiEnvironment(cb): # -> None:
    ...

def shutdownGuiEnvironment(): # -> None:
    ...

