"""
This type stub file was generated by pyright.
"""

import _jpype
from . import _jcustomizer

__all__ = ['JException']
@_jcustomizer.JImplementationFor("java.lang.Throwable", base=True)
class JException(_jpype._JException, internal=True):
    """ Base class for all ``java.lang.Throwable`` objects.

    Use ``issubclass(cls, JException)`` to test if a class is derived
    from ``java.lang.Throwable.``

    Use ``isinstance(obj, JException)`` to test if an object is a
    ``java.lang.Throwable``.

    """
    def message(self): # -> str:
        ...
    
    def stacktrace(self):
        """ Get a string listing the stack frame.

        Returns:
          A string with the classic Java ``printStackTrace`` result.
        """
        ...
    
    @property
    def args(self):
        ...
    


