"""
This type stub file was generated by pyright.
"""

import _jpype

__all__ = ['JPackage']
class _JPackageMeta(type):
    def __instancecheck__(self, other): # -> bool:
        ...
    
    def __subclasscheck__(self, other): # -> bool:
        ...
    


class JPackage(_jpype._JPackage, metaclass=_JPackageMeta):
    """ Gateway for automatic importation of Java classes.

    This class allows structured access to Java packages and classes.
    This functionality has been replaced by ``jpype.imports``, but is still
    useful in some cases.

    Only the root of the package tree needs to be declared with the ``JPackage``
    constructor. Sub-packages will be created on demand.

    For example, to import the w3c DOM package:

    .. code-block:: python

      Document = JPackage('org').w3c.dom.Document

    Under some situations such as a missing jar file, the resulting object
    will be a JPackage object rather than the expected java class. This
    results in rather challanging debugging messages. Due to this 
    restriction, the ``jpype.imports`` module is preferred. To prevent these
    types of errors, a package can be declares as ``strict`` which prevents
    expanding package names that do not comply with Java package name
    conventions.

    Args:
      path (str): Path into the Java class tree.

    Example:

      .. code-block:: python

        # Alias into a library
        google = JPackage("com").google

        # Access members in the library
        result = google.common.IntMath.pow(x,m)

    """
    ...


