"""
This type stub file was generated by pyright.
"""

import typing

_KEYWORDS = ...
def pysafe(s: str) -> typing.Optional[str]:
    """
    Given an identifier name in Java, return an equivalent identifier name in
    Python that is guaranteed to not collide with the Python grammar.

    """
    ...

