"""
This type stub file was generated by pyright.
"""

from . import _jcustomizer

"""
JPype Beans Module
------------------

This customizer finds all occurences of methods with get or set and converts
them into Python properties. This behavior is sometimes useful in programming
with JPype with interactive shells, but also leads to a lot of confusion.
Is this class exposing a variable or is this a property added JPype.  

As an unnecessary behavior that violates both the Python principle
*"There should be one-- and preferably only one --obvious way to do it."* and
the C++ principle *"You only pay for what you use"*.  This misfeature
was removed from the distribution as a default. However, given that it is
useful to have methods appear as properties, it was moved to a
an optional module.

To use beans as properties:

.. code-block:: python

  import jpype.beans

The beans property modification is a global behavior and applies retroactively
to all classes currently loaded.  Once started it can not be undone.
"""
@_jcustomizer.JImplementationFor("java.lang.Object")
class _BeansCustomizer:
    """ Add properties for get/set Bean patterns found in classes.  """
    def __jclass_init__(self): # -> None:
        ...
    


