"""
This type stub file was generated by pyright.
"""

import _jpype
from ._jclass import *
from ._jobject import *
from ._jarray import *
from ._jstring import *

"""
JPype Types Module
------------------

Optional module containing only the Java types and factories used by
JPype.  Classes in this module include ``JArray``, ``JClass``,
``JBoolean``, ``JByte``, ``JChar``, ``JShort``, ``JInt``, ``JLong``,
``JFloat``, ``JDouble``, ``JString``, ``JObject``, and ``JException``.

Example:

    .. code-block:: python

        from jpype.types import *

"""
__all__ = ['JArray', 'JClass', 'JBoolean', 'JByte', 'JChar', 'JShort', 'JInt', 'JLong', 'JFloat', 'JDouble', 'JString', 'JObject', 'JException']
class JBoolean(_jpype._JBoolean, internal=True):
    ...


class JByte(_jpype._JNumberLong, internal=True):
    ...


class JChar(_jpype._JChar, internal=True):
    ...


class JInt(_jpype._JNumberLong, internal=True):
    ...


class JShort(_jpype._JNumberLong, internal=True):
    ...


class JLong(_jpype._JNumberLong, internal=True):
    ...


class JFloat(_jpype._JNumberFloat, internal=True):
    ...


class JDouble(_jpype._JNumberFloat, internal=True):
    ...


